
Example TeamCity Kotlin DSL configuration to build the https://github.com/rodm/gradle-teamcity-plugin[Gradle TeamCity plugin]

There are versioned settings for multiple different setups, each is on a different branch, below is the branch name
and a description of the configuration.

* `master` - contains the latest project configuration with build configurations to build the plugin.

* `basic` - contains a project configuration with a single build configuration that builds and runs the unit tests
with Java 7

* `builds` - contains a project configuration with a number of build configurations that build and run either unit
tests or functional tests or sample tests. There is also a code quality build configuration that runs the
`sonarqube` task. The common build configuration used by all the build configurations is defined using a base build type.

* `template` - contains a project configuration with the same build configurations as the `builds` branch but they
are based on a build template.

Follow the steps below to import the settings into a TeamCity Server

* Create a VCS Root for the https://github.com/rodm/teamcity-settings[TeamCity settings] project in the 'Root project'
** Enter the project URL, https://github.com/rodm/teamcity-settings, in the Fetch URL field
** Enter the branch, refs/heads/_branch_, in the Default branch field, where _branch_ is either `basic`, `builds`,
`template` or `master`.

* Create a new sub-project under the Root project
** Enter a project name
** Enter the project ID 'GradleTeamCityPlugin'

* Select 'Versioned Settings'
** Select the option 'Synchronization enabled', select the VCS root created above then select 'use settings from VCS'
and set the format to 'Kotlin' and click the Apply button.
** A dialog should appear indicating existing settings have been detected, select the 'Import from VCS option'.
TeamCity should update the project and create a build configuration.

To make changes fork the project and update the VCS root URLs to use your own repository.

== Resources

Configuration as Code series by Anton Arhipov in 2019 from the TeamCity blog

. https://blog.jetbrains.com/teamcity/2019/03/configuration-as-code-part-1-getting-started-with-kotlin-dsl/[Part 1: Getting Started with Kotlin DSL]
. https://blog.jetbrains.com/teamcity/2019/03/configuration-as-code-part-2-working-with-kotlin-scripts/[Part 2: Working with Kotlin Scripts]
. https://blog.jetbrains.com/teamcity/2019/04/configuration-as-code-part-3-creating-build-configurations-dynamically/[Part 3: Creating Build Configurations Dynamically]
. https://blog.jetbrains.com/teamcity/2019/04/configuration-as-code-part-4-extending-the-teamcity-dsl/[Part 4: Extending the TeamCity DSL]
. https://blog.jetbrains.com/teamcity/2019/04/configuration-as-code-part-5-using-dsl-extensions-as-a-library/[Part 5: Using DSL extensions as a library]
. https://blog.jetbrains.com/teamcity/2019/05/configuration-as-code-part-6-testing-configuration-scripts/[Part 6: Testing Configuration Scripts]

Kotlin Configuration Scripts series by Hadi Hariri in 2016 & 2017 from the TeamCity blog

. https://blog.jetbrains.com/teamcity/2016/11/kotlin-configuration-scripts-an-introduction/[An Introduction]
. https://blog.jetbrains.com/teamcity/2016/12/kotlin-configuration-scripts-working-with-configuration-scripts/[Working with Configuration Scripts]
. https://blog.jetbrains.com/teamcity/2017/01/kotlin-configuration-scripts-creating-configuration-scripts-dynamically/[Creating Configuration Scripts Dynamically]
. https://blog.jetbrains.com/teamcity/2017/02/kotlin-configuration-scripts-extending-the-teamcity-dsl/[Extending the TeamCity DSL]
. https://blog.jetbrains.com/teamcity/2017/02/kotlin-configuration-scripts-testing-configuration-scripts/[Testing Configuration Scripts]
